# Generated by Django 3.0 on 2021-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_auto_20210702_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
