# Generated by Django 3.0 on 2021-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0007_auto_20210702_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
