# Generated by Django 3.0 on 2021-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_restaurant_rsimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=50)),
                ('icategory', models.CharField(choices=[('Non-Veg', 'NV'), ('Veg', 'VG')], default='Select', max_length=12)),
                ('price', models.IntegerField()),
                ('iimage', models.ImageField(default='ics.jpg', upload_to='Itemimages/')),
                ('itavailability', models.CharField(choices=[('Available', 'AV'), ('Not Available', 'NA')], default='None', max_length=20)),
            ],
        ),
    ]
