# Generated by Django 3.0 on 2021-07-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_itemlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='icategory',
            field=models.CharField(choices=[('NV', 'Non-Veg'), ('VG', 'Veg')], default='Select', max_length=12),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='itavailability',
            field=models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available')], default='None', max_length=20),
        ),
    ]
