# Generated by Django 3.0 on 2021-07-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20210702_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='icategory',
            field=models.CharField(choices=[('NV', 'Non-Veg'), ('VG', 'Veg'), ('Df', 'Select Item Type')], default='Select', max_length=12),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='itavailability',
            field=models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available'), ('Sl', 'Select Availability')], default='None', max_length=20),
        ),
    ]
